### ISSUE TITLE
UnsatisfiedLinkError when running example 1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jasantunes/reverx#1]
```
1. Download the code. I'm using Debian 6.0.6
2. Extract: $ unzip reverx-1.0.beta.zip
3. Run example as per Readme: reverx-1.0$ java -cp 
reverx-1.0.jar:jnetpcap-1.3b1.jar Language -p ftp.pcap --delim="\r\n" 21 0.1f 
30 ftp.in

Output:
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnetpcap in 
java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1681)
    at java.lang.Runtime.loadLibrary0(Runtime.java:840)
    at java.lang.System.loadLibrary(System.java:1047)
    at org.jnetpcap.nio.JMemory.<clinit>(JMemory.java:73)
    at traces.PcapFile.<init>(PcapFile.java:60)
    at Language.main(Language.java:355)




```

Original issue reported on code.google.com by `hugo.lee...@gmail.com` on 13 Nov 2012 at 2:51

**Comment by disasmwinnie** [comment]
Repasted it from GCode since imho this solves the issue:

I had the same issue. The point is, one has also to install jnetpcap.so into /usr/lib to get it working. I used the download package from jnetpcap-site with newest build (the version 1.3 expects libpcap in very old version).

**Comment by Tusaka** [comment]
When i ran the Language.java ,it showed me something as follows:

OpenJDK 64-Bit Server VM warning: You have loaded library /usr/lib/libjnetpcap.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/libjnetpcap.so: /usr/lib/libjnetpcap.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.jnetpcap.nio.JMemory.<clinit>(JMemory.java:73)
	at traces.PcapFile.<init>(PcapFile.java:70)
	at Language.main(Language.java:435)

could you help me to fix it out? thank you very much!

**Comment by disasmwinnie** [comment]
This ``wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)`` looks like you installed the 32bit-version of jnetpcap. Get the 64bit-Version.

If the error message or parts of it apear again, pls post how you installed it and whether you have some hardened kernel running.

**Comment by Tusaka** [comment]
Thank you very much! it worked.

**Comment by BigBuilding** [comment]
This problem that how to input parameter and get protocol state machine has beaten me. 
Will you please give me some instruction to get the binary-based protocols and text-based protocols state machine ?

**Comment by Tusaka** [comment]
Just look  through the source code，pay attention to code that parse the options. For example the code after line 403 in Language.java.
